
   

void imprimirserial() {
  Serial.println("----------------------------------------------------");
  Serial.print("Tensão RMS  sem ajuste");
  Serial.print(Tensao); //
  Serial.print("V  ");
  Serial.println("");
  Serial.print("Corrente RMS sem ajuste  ");
  Serial.print(Corrente);
  Serial.print("A  ");
  Serial.println("");
  Serial.print("Corrente RMS  ");
  Serial.print(Corrente * M_Corrente);
  Serial.print("A  ");
  Serial.println("");
  Serial.print("Potência Ativa sem ajuste ");
  Serial.print(P_Real);
  Serial.print("W  ");
  Serial.println("");
  Serial.print("Potência Ativa  ");
  Serial.print(P_Real*M_P_Real);
  Serial.print("W  ");
  Serial.println("");
  //Serial.print("Potência Ativa Fundamental ");
  //Serial.print(P_Real_Fundamental*M_P_Real);
  //Serial.print("W  ");
  ///Serial.println("");
  Serial.print("Potência Reativa sem ajuste  ");
  Serial.print(P_Reativa);
  Serial.print("VAr  ");
  Serial.println("");
  Serial.print("Potência Reativa  ");
  Serial.print(P_Reativa* M_P_Reativa);
  Serial.print("VAr  ");
  Serial.println("");
  //Serial.print("Potência Reativa Fundamental ");
  //Serial.print(P_Reativa_Fundamental*M_P_Reativa);
  // Serial.print("VAr  ");
  // Serial.println("");
  Serial.print("Potência Aparente sem ajuste ");
  Serial.print(P_Aparente);
  Serial.print("VA  ");
  Serial.println("");
  Serial.print("Potência Aparente  ");
  Serial.print(P_Aparente * M_P_Aparente);
  Serial.print("VA  ");
  Serial.println("");
  Serial.print("Potência Aparente calculada ");
  Serial.print((Tensao * M_Tensao) * (Corrente * M_Corrente));
  Serial.print("VA  ");
  Serial.println("");
  Serial.print("Fator de Potência sem Ajuste ");
  Serial.print(FP);
  Serial.println("");
  Serial.print("Fator de Potência  ");
  Serial.print(FP* M_FP);
  Serial.println("");
  Serial.println("");
  Serial.print("Fator de Potência Calculado ");
  Serial.print(((P_Real*M_P_Real)/(Tensao * M_Tensao) * (Corrente * M_Corrente)));
  Serial.println("");
  Serial.print("Temperatura CI  ");
  Serial.print(Temperatura * M_Temperatura);
  Serial.print("ºC ");
  Serial.println("");
  Serial.print("Potencia Ativa Harmonica ");
  Serial.print(P_Real_Harmonica * M_P_Real_Harmonica);
  Serial.print("PH ");
  Serial.println("");
  Serial.print("Frequencia sem ajustes ");
  Serial.print(Freq_Epsilon);
  Serial.print("Hz ");
  Serial.println("");
  Serial.print("Frequencia ");
  Serial.print(Freq_Epsilon * M_Frequencia);
  Serial.print("Hz ");
  Serial.println("");
  Serial.println("----------------------------------------------------");
}
